# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles /workspace//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named eeprom

# Build rule for target.
eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eeprom
.PHONY : eeprom

# fast build rule for target.
eeprom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eeprom.dir/build.make CMakeFiles/eeprom.dir/build
.PHONY : eeprom/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named strip

# Build rule for target.
strip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strip
.PHONY : strip

# fast build rule for target.
strip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strip.dir/build.make CMakeFiles/strip.dir/build
.PHONY : strip/fast

#=============================================================================
# Target rules for targets named ams-function-generator

# Build rule for target.
ams-function-generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ams-function-generator
.PHONY : ams-function-generator

# fast build rule for target.
ams-function-generator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/build
.PHONY : ams-function-generator/fast

source/encoder.obj: source/encoder.c.obj
.PHONY : source/encoder.obj

# target to build an object file
source/encoder.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/encoder.c.obj
.PHONY : source/encoder.c.obj

source/encoder.i: source/encoder.c.i
.PHONY : source/encoder.i

# target to preprocess a source file
source/encoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/encoder.c.i
.PHONY : source/encoder.c.i

source/encoder.s: source/encoder.c.s
.PHONY : source/encoder.s

# target to generate assembly for a file
source/encoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/encoder.c.s
.PHONY : source/encoder.c.s

source/i2c_master.obj: source/i2c_master.c.obj
.PHONY : source/i2c_master.obj

# target to build an object file
source/i2c_master.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/i2c_master.c.obj
.PHONY : source/i2c_master.c.obj

source/i2c_master.i: source/i2c_master.c.i
.PHONY : source/i2c_master.i

# target to preprocess a source file
source/i2c_master.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/i2c_master.c.i
.PHONY : source/i2c_master.c.i

source/i2c_master.s: source/i2c_master.c.s
.PHONY : source/i2c_master.s

# target to generate assembly for a file
source/i2c_master.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/i2c_master.c.s
.PHONY : source/i2c_master.c.s

source/lcd_menu.obj: source/lcd_menu.c.obj
.PHONY : source/lcd_menu.obj

# target to build an object file
source/lcd_menu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/lcd_menu.c.obj
.PHONY : source/lcd_menu.c.obj

source/lcd_menu.i: source/lcd_menu.c.i
.PHONY : source/lcd_menu.i

# target to preprocess a source file
source/lcd_menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/lcd_menu.c.i
.PHONY : source/lcd_menu.c.i

source/lcd_menu.s: source/lcd_menu.c.s
.PHONY : source/lcd_menu.s

# target to generate assembly for a file
source/lcd_menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/lcd_menu.c.s
.PHONY : source/lcd_menu.c.s

source/liquid_crystal_i2c.obj: source/liquid_crystal_i2c.c.obj
.PHONY : source/liquid_crystal_i2c.obj

# target to build an object file
source/liquid_crystal_i2c.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/liquid_crystal_i2c.c.obj
.PHONY : source/liquid_crystal_i2c.c.obj

source/liquid_crystal_i2c.i: source/liquid_crystal_i2c.c.i
.PHONY : source/liquid_crystal_i2c.i

# target to preprocess a source file
source/liquid_crystal_i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/liquid_crystal_i2c.c.i
.PHONY : source/liquid_crystal_i2c.c.i

source/liquid_crystal_i2c.s: source/liquid_crystal_i2c.c.s
.PHONY : source/liquid_crystal_i2c.s

# target to generate assembly for a file
source/liquid_crystal_i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/liquid_crystal_i2c.c.s
.PHONY : source/liquid_crystal_i2c.c.s

source/main.obj: source/main.c.obj
.PHONY : source/main.obj

# target to build an object file
source/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/main.c.obj
.PHONY : source/main.c.obj

source/main.i: source/main.c.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/main.c.i
.PHONY : source/main.c.i

source/main.s: source/main.c.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/main.c.s
.PHONY : source/main.c.s

source/pwm.obj: source/pwm.c.obj
.PHONY : source/pwm.obj

# target to build an object file
source/pwm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/pwm.c.obj
.PHONY : source/pwm.c.obj

source/pwm.i: source/pwm.c.i
.PHONY : source/pwm.i

# target to preprocess a source file
source/pwm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/pwm.c.i
.PHONY : source/pwm.c.i

source/pwm.s: source/pwm.c.s
.PHONY : source/pwm.s

# target to generate assembly for a file
source/pwm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/pwm.c.s
.PHONY : source/pwm.c.s

source/spi.obj: source/spi.c.obj
.PHONY : source/spi.obj

# target to build an object file
source/spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/spi.c.obj
.PHONY : source/spi.c.obj

source/spi.i: source/spi.c.i
.PHONY : source/spi.i

# target to preprocess a source file
source/spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/spi.c.i
.PHONY : source/spi.c.i

source/spi.s: source/spi.c.s
.PHONY : source/spi.s

# target to generate assembly for a file
source/spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/spi.c.s
.PHONY : source/spi.c.s

source/uart.obj: source/uart.c.obj
.PHONY : source/uart.obj

# target to build an object file
source/uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/uart.c.obj
.PHONY : source/uart.c.obj

source/uart.i: source/uart.c.i
.PHONY : source/uart.i

# target to preprocess a source file
source/uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/uart.c.i
.PHONY : source/uart.c.i

source/uart.s: source/uart.c.s
.PHONY : source/uart.s

# target to generate assembly for a file
source/uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ams-function-generator.dir/build.make CMakeFiles/ams-function-generator.dir/source/uart.c.s
.PHONY : source/uart.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... eeprom"
	@echo "... flash"
	@echo "... hex"
	@echo "... strip"
	@echo "... ams-function-generator"
	@echo "... source/encoder.obj"
	@echo "... source/encoder.i"
	@echo "... source/encoder.s"
	@echo "... source/i2c_master.obj"
	@echo "... source/i2c_master.i"
	@echo "... source/i2c_master.s"
	@echo "... source/lcd_menu.obj"
	@echo "... source/lcd_menu.i"
	@echo "... source/lcd_menu.s"
	@echo "... source/liquid_crystal_i2c.obj"
	@echo "... source/liquid_crystal_i2c.i"
	@echo "... source/liquid_crystal_i2c.s"
	@echo "... source/main.obj"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/pwm.obj"
	@echo "... source/pwm.i"
	@echo "... source/pwm.s"
	@echo "... source/spi.obj"
	@echo "... source/spi.i"
	@echo "... source/spi.s"
	@echo "... source/uart.obj"
	@echo "... source/uart.i"
	@echo "... source/uart.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

